name: hfdem-A13-5.15
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  push:
    paths:
      - .github/workflows/hfdem-kernel-a13-5.15.yml  # Runs when this workflow file is updated\
  workflow_dispatch:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Official
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      kernelsu_branch_other:
        required: false
        type: string
        default: ""
  
jobs:
  build-hfdem-kernel-a13-5-15-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
        - sub_level: "233"
          os_patch_level: "2025-03"
          revision: "r1"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: "android13"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}